### PR TITLE
test: state methods in concrete env

### LINKED ISSUE #34: Test state methods in Concrete environment
> **[ODHack 5.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

# Rationale

Currently, the Concrete environment is poorly tested.

# Implementation

This depends on #33 being implemented. Once that is done, the mock statedb in `concrete/mock` can be moved to/reimplemented within `concrete/api` to have an in-memory statedb for testing. Both execution and gas usage should be tested.

At the moment, the state methods are:

```go
type Environment interface {
	// ...

	StorageLoad(key common.Hash) common.Hash
	StorageStore(key common.Hash, value common.Hash)
	Log(topics []common.Hash, data []byte)

	GetBalance(address common.Address) *uint256.Int
	GetCode(address common.Address) []byte
	GetCodeSize() int
	GetExternalBalance(address common.Address) *uint256.Int
	GetExternalCode(address common.Address) []byte
	GetExternalCodeSize(address common.Address) int
	GetExternalCodeHash(address common.Address) common.Hash
}
```

Note two more methods will be added by #31 .

### PR DESCRIPTION
**Pull request by fishonamos**
Closes #34

### CODE REVIEW

**Review by therealbytes — CHANGES_REQUESTED** [review]
Can you add checks for the exact amount of gas being used like it is done in other tests?

**Comment by therealbytes** [comment]
You can find an example of gas usage being checked in `TestCallMethods` in the same file.

For instance:

```golang
r.Equal(env.Gas(), gas-params.ColdAccountAccessCostEIP2929-useGas)
```

The gas left must be the initial gas minus the used gas, in this case `params.ColdAccountAccessCostEIP2929+useGas`.

You can see how the methods' gas cost is calculated in `methods_go.go`.

**Comment by fishonamos** [comment]
> You can find an example of gas usage being checked in `TestCallMethods` in the same file.
> 
> For instance:
> 
> ```go
> r.Equal(env.Gas(), gas-params.ColdAccountAccessCostEIP2929-useGas)
> ```
> 
> The gas left must be the initial gas minus the used gas, in this case `params.ColdAccountAccessCostEIP2929+useGas`.
> 
> You can see how the methods' gas cost is calculated in `methods_go.go`.
This works for tests that use only constant gas. It fails when I try same for dynamic gas.

**Comment by fishonamos** [comment]
> You can find an example of gas usage being checked in `TestCallMethods` in the same file.
> 
> For instance:
> 
> ```go
> r.Equal(env.Gas(), gas-params.ColdAccountAccessCostEIP2929-useGas)
> ```
> 
> The gas left must be the initial gas minus the used gas, in this case `params.ColdAccountAccessCostEIP2929+useGas`.
> 
> You can see how the methods' gas cost is calculated in `methods_go.go`.


This works for test cases that uses only constant gas.  And call methods already have functions for getting dynamic gas in mock. StateMethods don't

**Comment by fishonamos** [comment]
For example, I tried the below test for GetExternalCode which uses both a constant gas and dynamic gas and it still failed. 

```
                usedGas := initialGas - env.contract.Gas
		
		expectedGas, err := gasAccountAccessMinusWarm(env, address)
		r.NoError(err, "Gas calculation should not error")
		
		r.Equal(expectedGas, usedGas)
		r.Equal(balance, loadedBalance)
```

Other methods like GetCode and GetCode Size work correctly because they use constant gas.

**Comment by therealbytes** [comment]
You should account for both the constant and dynamic code and not reuse the gas functions in methods_go.go since those are part of the code we are testing.

For instance, calling `GetExternalCode` on an address that is no in the access list costs `WarmStorageReadCostEIP2929 + (ColdAccountAccessCostEIP2929 - WarmStorageReadCostEIP2929) = ColdAccountAccessCostEIP2929`.

You could test that the gas cost is correct both for cold and warm reads with something like:

```golang
func TestStateMethods(t *testing.T) {
	r := require.New(t)
	config := EnvConfig{IsStatic: false, IsTrusted: false}
	meterGas := true

	env, statedb, _, _ := NewMockEnvironment(WithConfig(config), WithMeterGas(meterGas))
	gas := uint64(1e6)
	warmAddr := common.BytesToAddress([]byte("warm"))
	statedb.(*state.StateDB).AddAddressToAccessList(warmAddr)

	t.Run("GetExternalCode", func(t *testing.T) {
		// Setup
		code := []byte{0x61, 0x61, 0x61, 0x61}
		statedb.(*state.StateDB).SetCode(warmAddr, code)
		// Warm access
		env.contract.Gas = gas
		loadedCode := env.GetExternalCode(warmAddr)
		r.Equal(code, loadedCode)
		r.Equal(env.Gas(), gas-params.WarmStorageReadCostEIP2929)
		// Cold access
		env.contract.Gas = gas
		env.GetExternalBalance(common.BytesToAddress([]byte("GetExternalCode.cold")))
		r.Equal(env.Gas(), gas-params.ColdAccountAccessCostEIP2929)
	})
}

**Comment by fishonamos** [comment]
Yes! All now passing! Kindly review @therealbytes

**Comment by therealbytes** [comment]
Changes merged in #75.

**Pull request closed without merging**
