### PR TITLE
Feat: Implement mockBlockContext

### PR DESCRIPTION
**Pull request by rajeshkumarrobert**
Implements #37

### CODE REVIEW

**Comment by rajeshkumarrobert** [comment]
Hi @therealbytes🫡 Could you please review the PR?

**Review by therealbytes — CHANGES_REQUESTED** [review]
**Block context**

Right concept, but it needs some changes in implementation.
- This is an object that will be used for testing in the place of a block context object following the `concrete/api.BlockContext` interface. There is no need for it to work the same way under the hood as geth's block context. `CanTransfer`, `Transfer`, `L1CostFunc` are not used in the concrete interface so they shouldn't be in the mock.
- `GetHash` should be implemented and it should be implemented in a way to makes testing easy and readable.
- Formatting could be better.

The code below should be a good start to implement this changes. Let me know how it goes.

```golang
type mockBlockContext struct {
	coinbase    common.Address
	gasLimit    uint64
	blockNumber uint64
	time        uint64
	difficulty  *uint256.Int
	baseFee     *uint256.Int
	random      common.Hash
	blockHashes map[uint64]common.Hash
}

func NewMockBlockContext() *mockBlockContext {
	return &mockBlockContext{
		coinbase:    common.Address{},
		gasLimit:    0,
		blockNumber: 0,
		time:        0,
		difficulty:  uint256.NewInt(0),
		baseFee:     uint256.NewInt(0),
		random:      common.Hash{},
		blockHashes: make(map[uint64]common.Hash),
	}
}

func (m *mockBlockContext) SetBlockHash(blockNumber uint64, hash common.Hash) {
	m.blockHashes[blockNumber] = hash
}

func (m *mockBlockContext) SetGasLimit(gasLimit uint64) {
	m.gasLimit = gasLimit
}

func (m *mockBlockContext) SetBlockNumber(blockNumber uint64) {
	m.blockNumber = blockNumber
}

// ...

func (m *mockBlockContext) GetHash(blockNumber uint64) common.Hash { return m.blockHashes[blockNumber] }
func (m *mockBlockContext) GasLimit() uint64                       { return m.gasLimit }
func (m *mockBlockContext) BlockNumber() uint64                    { return m.blockNumber }
// ...
```

**Caller**
- Call inputs are ignored, so it is not possible to test they are being passed correctly.
- "Expected" is not the right word. The outputs are being pre-defined, not expected.

I think instead of setting the outputs, the mock object should expose methods to set the call handlers like this:

```golang
type mockCaller struct {
	callFn         func(common.Address, []byte, uint64, *uint256.Int) ([]byte, uint64, error)
	// ...
}

func NewMockCaller() *mockCaller {
	return &mockCaller{}
}

func (c *mockCaller) SetCallFn(fn func(common.Address, []byte, uint64, *uint256.Int) ([]byte, uint64, error)) {
	c.callFn = fn
}

// ...

func (c *mockCaller) Call(addr common.Address, input []byte, gas uint64, value *uint256.Int) ([]byte, uint64, error) {
	if c.callFn == nil {
		return nil, 0, nil
	}
	return c.callFn(addr, input, gas, value)
}

// ...

```

**Comment by rajeshkumarrobert** [comment]
Hi @therealbytes  I have updated the review comments, Could you please have a look?

**Review by therealbytes — CHANGES_REQUESTED** [review]
Looks good. Can you edit the formatting so it is consistent with the rest of the code?
- Multi-line function declarations should be separated by an empty line.
- Single-line getters for an object should not have an empty line between them.

See the code example I provided before for an example of this.

**Review by therealbytes — APPROVED** [review]
LGTM

**Pull request merged**
