### PR TITLE
feat: Debugf function for better debugging

### LINKED ISSUE #35: Add a Debugf helper function to the Concrete environment
# Rationale

Right now, the environment exposes `Debug(msg string)` which is simple and easy to integrate with WASM but also cumbersome to use when many values must be printed e.g.,

```go
env.Debug(fmt.Sprintf("Lorem ipsum a=%v b=%v", a, b)
```

# Implementation

Add a `Debugf(msg string, ctx ...interface{})` method that generates a string with the format `<msg> <name1>=<value1> <name2>=<value2> ...` and calls `Debug` with it. The code above should become:

```go
env.Debugf("Lorem ipsum", "a", a, "b", b)
```

Feedback wanted regarding the naming of the method and the formatting of the string.

> **[ODHack 4.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

### PR DESCRIPTION
**Pull request by kamuik16**
Closes #35

### CODE REVIEW

**Comment by kamuik16** [comment]
Do let me know if something is not aligned with what you expected. Thanks!

**Comment by therealbytes** [comment]
This is in the right direction. Just a few issues:
1. String values should be escaped
2. Errors should be handled instead of panicking
3. Debugf should be added to the `Environment` interface

I think the simplest way to do 1 and 2 for now is to use a logging library for formatting instead of implementing it from scratch. e.g.,

```golang
func debugfFormat(msg string, ctx ...interface{}) string {
	var buf bytes.Buffer
	logger := log.NewLogger(log.NewTerminalHandlerWithLevel(&buf, log.LevelDebug, true))
	logger.Debug(msg, ctx...)
	return buf.String()
}
```

**Comment by kamuikatsurgi** [comment]
@therealbytes implemented your suggestions ser! Let me know if I did something wrong as I am still somewhat new to Go.

**Comment by kamuik16** [comment]
Updated the code @therealbytes ser! Let me know if I did something wrong as I am still somewhat new to Go.

**Review by therealbytes — APPROVED** [review]

**Pull request merged**
